---

- name: check for unsupported target operating system
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported"
  when: not (ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu')

- name: Debian | run apt update
  sudo: yes
  apt: update_cache=yes
  tags:
    - autopostgresqlbackup

- name: Debian | Ensure autopostgresqlbackup and other required packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - autopostgresqlbackup
    - mailutils
  tags:
    - autopostgresqlbackup

- name: apply autopostgresqlbackup configuration
  sudo: yes
  template:
    src: autopostgresqlbackup.j2
    dest: /etc/default/autopostgresqlbackup
    group: root
    owner: root
    mode: 0600
  tags:
    - autopostgresqlbackup

- name: Make sure backup directory exists and is writeable (owned) by postgres user
  file:
    path={{ autopostgresqlbackup_backup_directory }}
    state=directory
    recurse=yes
    owner=postgres
    group=postgres
  tags:
    - autopostgresqlbackup

- name: remove the cron.daily file
  sudo: yes
  file: path=/etc/cron.daily/autopostgresqlbackup state=absent
  tags:
    - autopostgresqlbackup

- name: add autopostgresqlbackup cron job
  sudo: yes
  cron:
    name: "autopostgresqlbackup"
    minute: "{{ autopostgresqlbackup_cron.minute }}"
    hour: "{{ autopostgresqlbackup_cron.hour }}"
    day: "{{ autopostgresqlbackup_cron.day }}"
    month: "{{ autopostgresqlbackup_cron.month }}"
    weekday: "{{ autopostgresqlbackup_cron.weekday }}"
    user: root
    job: "/usr/sbin/autopostgresqlbackup"
  tags:
    - autopostgresqlbackup
